### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by brunsgaard** [AlejandroFrias/case-conversion#1]
I see this when importing case-conversion, python 3.5.2.

```
(asgt) ⋊> ~/e/vml-model-econbankrec on master ⨯ pip install -U case-conversion 
Requirement already up-to-date: case-conversion
Requirement already up-to-date: regex>=2016.2.25

(asgt) ⋊> ~/e/vml-model-econbankrec on master ⨯ python -c 'import case_conversion'  
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/brunsgaard/.virtualenvs/asgt/lib/python3.5/site-packages/case_conversion/__init__.py", line 1, in <module>
    from case_conversion import (
ImportError: cannot import name 'camelcase'

```

**Comment by lucaswiman** [comment]
I think this was fixed by https://github.com/AlejandroFrias/case-conversion/pull/2, though it looks like that hasn't been deployed to pypi yet.

**Comment by brunsgaard** [comment]
Yo are right #17655f4b099ac840712dd95ad989f7b41301b83c, fixes this issue

**Comment by AlejandroFrias** [comment]
Sorry I forgot to deploy to PyPi after that fix. Just deployed.
